### ISSUE TITLE
LeGoReader doesn't run anymore

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Lima#23]
It seems that the LegoReader is broken I get the following error when running it
@vaap1997 did you change anything recently?

<img width="1060" alt="screen shot 2018-10-03 at 17 10 00" src="https://user-images.githubusercontent.com/3928502/46439690-374d4000-c72f-11e8-8a95-b67cbc61a121.png">

**Comment by vaap1997** [comment]
No I don´t. I will take a look on the script to see what is happening.

**Comment by vaap1997** [comment]
@agrignard I try with tree different computers and it work perfect in each case. I change the parameters and also the color calibration and everything works fine. Did you do something before run it? In which part appears the error? Let me know if you could run it. I just did a push to put all sketches related with P3D, but it is not an error.

**Comment by agrignard** [comment]
I still have this issue after pulling the last update with Processing 3.3.7 and Mac Os X 10.11.6.

I will try to dig it more in details

**Comment by agrignard** [comment]
@vaap1997 Are you sure you commit every files? maybe you ahe something in local? For instance a parameters.json or something like that?

**Comment by yasushisakai** [comment]
hi @vaap1997 !
regarding this issue, same here, macOS 10.13.6, processing 3.3.7,\
line 215 @ Mesh.pde, NPE

**Comment by agrignard** [comment]
mmm I manage to make it works one but it raises this error

`````
java.lang.NullPointerException
	at processing.opengl.Texture.copyBufferFromSource(Texture.java:827)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at processing.video.Capture.read(Unknown Source)
	at LegoReader.captureEvent(LegoReader.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at processing.video.Capture.fireCaptureEvent(Unknown Source)
	at processing.video.Capture.invokeEvent(Unknown Source)
	at processing.video.Capture$2.bufferFrame(Unknown Source)
	at org.gstreamer.elements.BufferDataAppSink$AppSinkNewBufferListener.newBuffer(BufferDataAppSink.java:163)
	at org.gstreamer.elements.AppSink$2.callback(AppSink.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:485)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:515)


`````

**Comment by agrignard** [comment]
So there is an issue in setColorPattern()whre it seems that colorPatterns is null most of the time the super weird thing is that sometime (let's say one out of 5) I can make it work

**Comment by vaap1997** [comment]
Yeah, super weird. It always work for me. Well now I know where is the problem so I will check the function.

**Comment by agrignard** [comment]
Super very helpful. I guess it's a very tiny details.

I am sure you will figure it out! 

Are you sure you have everything commited? What grid.json and points.json maybe it comes from those files?

**Comment by agrignard** [comment]
this commit is working
https://github.com/CityScope/CSL_Lima/tree/3324b6efb5e5851d825e8cd5ae389ea2e716115e

so it means that something has been introduce later that make it crashes

**Comment by agrignard** [comment]
Ok so @vaap1997 thanks for the effort

it seems that the error is in this commit
https://github.com/CityScope/CSL_Lima/commit/91d622455ccf8b364024beb19af0e1d37bf5b42d

as it crashes already on the same line

**Comment by vaap1997** [comment]
@agrignard I just did a new commit, to solve references. Let me know if there is still a problem running it

**Comment by agrignard** [comment]
Still here

**Comment by vaap1997** [comment]
@agrignard I have done two commits and I have prove it in a computer I told you about. Let me know if everything works. The first commit is with the change that was causing troubles and the other is with all the other changes.
