### ISSUE TITLE
NPE in Canvas

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Lima#27]
<img width="701" alt="screen shot 2018-10-27 at 2 00 25 pm" src="https://user-images.githubusercontent.com/3928502/47607659-c24ced80-d9f0-11e8-8890-c07dd6b877c2.png">

This happen after few hours of running

**Comment by vaap1997** [comment]
I am running it, lets see at what time this appears and why.

**Comment by vaap1997** [comment]
@agrignard I had run the script for about 6 hours and it didn´t crush. On monday, I will check it on a  computer with a higher procesador like the last time. I will play with the frameRatio to reduce the CPU usage, mine didn´t crush but I could listen the computer fan working hard and the computer usage was oscillating from 150-250%.

**Comment by agrignard** [comment]
Ok I have a good news the script finally runs for more than few hours. At least it last for one night. let's see how long it goes. What I did in the last commit is that I sent the information to UDP only if the grid is different. Before the information was always sent which I guess gave a problem in term of memory. 

Let's see and let's cross the finger

**Comment by agrignard** [comment]
@vaap1997 were you abel to reproduce this bug? It always happen after a while on my machine.

It would be great to track this one, so we can have a working scanning (now the scanning need to be restarted evry couple of hours which make it impossible to use for real deployment)

**Comment by agrignard** [comment]
This one is still happening in the master I will investigate if it disappears in the dev branch

**Comment by agrignard** [comment]
Ok so bad news this is also happening in the dev branch (roughly after something like 6 hours of running)...

**Comment by agrignard** [comment]
@JesusGarcia98 any chance to fix this issue?

**Comment by JesusGarcia98** [comment]
Sorry for taking so long to reply, for some reason I did not receive the notification of your message. Have you tried hiding the windows that are not being used? (I added a method to BlockReader, PatternView and ColorRange to toggle their visibility) I know that helps reducing the use of resources, so it might help.

Still, I will try to find other possible solutions.

**Comment by JesusGarcia98** [comment]
I added a minor thing and the program has been running normally for more than 10 hours now.

**Comment by agrignard** [comment]
i am trying to test it.

right now I have this error when i launch it 

'''''
java.lang.NullPointerException
	at processing.opengl.Texture.copyBufferFromSource(Texture.java:827)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at processing.video.Capture.read(Unknown Source)
	at LegoReader.captureEvent(LegoReader.java:219)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at processing.video.Capture.fireCaptureEvent(Unknown Source)
	at processing.video.Capture.invokeEvent(Unknown Source)
	at processing.video.Capture$2.bufferFrame(Unknown Source)
	at org.gstreamer.elements.BufferDataAppSink$AppSinkNewBufferListener.newBuffer(BufferDataAppSink.java:163)
''''''

**Comment by JesusGarcia98** [comment]
That is unexpected, I do not get any errors when I launch it on my Mac or in a PC. From what I can understand from that error, you are having an issue with the camera (it might not be detecting it?).

**Comment by agrignard** [comment]
null pointer exception after 4 hours of test in
**canvasCamera.endDraw();**

**Comment by JesusGarcia98** [comment]
Just for curiosity, are you running it on PC or on a laptop? I will try to replicate the exact setup you used.

**Comment by agrignard** [comment]
I am running it on on a mac mini with the last mac os. It is also running another simulation on it. 

I restart it yesterady and it is crashed this morning. It's a pretty hard to track bug...

**Comment by JesusGarcia98** [comment]
I think I have some clues of what is happening:

1) canvasCamera is considered null right after the line: 
    configuration.drawWarp(canvasCamera);
    Which means that somehow that method is making canvasCamera unavailable for the following line
    (canvasCamera.endDraw();)

2) configuration.drawWarp(canvasCamera) calls the draw() method of the WarpedPerspective class.
     From what I have been investigating, a class should not have a draw() method unless it extends
     PApplet. If a class not extending it has to draw something, the method should have a different
     name, like: display().

3) Creating a draw() method in a class like WarpedPerspective (which does not extend PApplet),
     basically means creating an extra draw() method that will also be executed 60 times per second
     (like the draw() method in main), since draw is a reserved word. To avoid this, the OOP examples in
     Processing simply change the method's name.

4) Now, here is what I believe is happening when the draw() in main and the draw() in
     WarpedPerspective interact. The former will be calling the latter 60 times per second, while the
     latter is also executing its own code 60 times per second. With time, it comes a point where they
     get out of sync and the former tries to call canvasCamera while the latter is not done using it, which
     is interpreted as canvasCamera being null.

It might sound really simple to change the draw method name in the classes not extending PApplet, but it might do the trick conceptually speaking, since it will be following the examples included in the Processing documentation. I am yet to test this, but I thought it would be a good idea to share what I have learnt.

**Comment by agrignard** [comment]
@JesusGarcia98 it would be great if we can finally catch this bug. This is so time consuming on my side to restart everyday this scanner. 

Do you think you will be able to implement what the 4 point you just described. For sure there is somethign wrong it the way it is implemented right now.

If you have anything new please let me knwo so I can test it. Right now it still crashes after a while

**Comment by JesusGarcia98** [comment]
I have implemented the mentioned changes in the dev branch. I will test it tonight. Hopefully it will do the trick this time.

**Comment by agrignard** [comment]
Ok I just relaunch it with the last dev version. Let's see Finger crossed

**Comment by agrignard** [comment]
Unfortunately I still have this NullPointerException.

you mentioned about closing some of the windows? which one were you speaking about?

**Comment by JesusGarcia98** [comment]
I added methods to hide all the PApplets (except the main one), the buttons to do it are in the documentation and in the comments. I usually hide the ColorRange window.

Something weird is that whenever I test the code in a PC (with a webcam) running Windows 10, the program does not crash. Could it be possible that is due to the Processing version for Mac?

**Comment by agrignard** [comment]
1. How long do you test it on PC? it uselly crashed after at least 3-4 hours( which sounds like a memory leak)

2. Maybe one track to explore is P3D vs P2D

**Comment by JesusGarcia98** [comment]
1. I tested it for 24 - 25 hours. I am testing it again with this new version. Tomorrow I will try testing it
    on a spare MacBook in the office and see if it works there.

2. I will be exploring other ideas, like merging all the windows in one or even rethink the way it is 
    implemented.

**Comment by agrignard** [comment]
So to be more precise my configuration is a bit more complex than just a computer
0. It's running on a recent mac mini
1. I am using 2 screens one to control the computer (the scanning) and one to display a Gama simulation on a physical table (through a projector)
2. This simulation is running a GAMA model that you can find here https://github.com/agrignard/URBAM which is listening to the Processing script in order to update a grid.

I don't see how this 2 point could have any impact but just in case. 

@JesusGarcia98 can you point me the documentation that explain how to turn off the windows?

**Comment by JesusGarcia98** [comment]
Well, when I test it, I do not have another simulation running. Maybe the scanner, as it is right now, is still consuming too much memory when all the windows are shown.

To hide a window, click inside it, then press 's'. If you want to reopen them, go the main window and press:
'b' to reopen BlockReader
'c' to reopen ColorRange
'p' to reopen Patterns

**Comment by agrignard** [comment]
Ok so what about having a key that close everything I mean ones everything is calibrated we don't have to display what the camera sees and the results. Maybe that can help to track this issue by not rendering anything ones the calibration are made

**Comment by JesusGarcia98** [comment]
I was thinking about that too. I will have to rework some things in order to keep reading the results from the scan, since right now, hiding the main window also stops reading from the camera. But it should not be much of a problem to implement.

The core thing we need are the results of the scan (grid, indices), right?

**Comment by agrignard** [comment]
Yep you're right what is important at the end (once the calibrations is done) is only to send the scan results (through UDP and ultimately through cityIO  web server but I 'am not sure this is working (if yes then it can be useful to see how you make it in order to fix this issue  https://github.com/CityScope/CS_CityIO_Backend/issues/61)

**Comment by agrignard** [comment]
Also I am thinking that maybe a multi threading approach can solve the solution. Basically configuration.drawWarp(canvasCamera); and the main draw() function could be called in 2 different thread. LIke what is done here (https://github.com/CityScope/CS_Cooper-Hewitt/blob/master/ABMobility/ABM.pde line 102)

**Comment by agrignard** [comment]
There is also a clear increase of the memory used by this software which should be constant. there is no addition of object or what so ever that would justify the increase in memory. So I am still strongly convince that there is a memory leak somewhere (like a list that is not clear for instance) that makes this memory increase and then produce a crash at some point; However this kind of memory leak are pretty hard to track (maybe there is a profiler for processing? https://stackoverflow.com/questions/6322783/is-there-any-available-processing-program-profiler ) especially as I didn't write this code.

**Comment by JesusGarcia98** [comment]
I will try to see if I can come up with a simpler approach to the scanner. I know this software has methods that create new lists or overwrite old ones while running, which would explain the volatile use of memory. I think right now the program might be too focused on calibrating, instead of sending results, which makes it more complex than it needs to be.

**Comment by agrignard** [comment]
@JesusGarcia98 a quick and dirty solution would be to have a script that rerun the processign software let's say every N hour. Are you interested to have a look to make it? On mac os this can be done using https://ole.michelsen.dk/blog/schedule-jobs-with-crontab-on-mac-osx.html I guess there is the same for windows.

**Comment by agrignard** [comment]
so this scritp is working 
https://github.com/CityScope/CSL_Lima/blob/dev/projects/LegoReader/automaticScript.sh

However the crontab is failing.

This is how to edit the crontan file

``````
env EDITOR=nano crontab -e
``````
and here is the file content
``````
YY XX * * *  /Users/Arno/Projects/GitHub/CSL_Lima/projects/LegoReader/automaticScript.sh
``````

YY : minute and XX:hour


This is the error sent in var/mail

`````
From Arno@Arno.local  Wed Mar 27 12:21:02 2019
Return-Path: <Arno@Arno.local>
X-Original-To: Arno
Delivered-To: Arno@Arno.local
Received: by Arno.local (Postfix, from userid 501)
        id 4555D187D9DC; Wed, 27 Mar 2019 12:21:02 -0400 (EDT)
From: Arno@Arno.local (Cron Daemon)
To: Arno@Arno.local
Subject: Cron <Arno@Arno> /Users/Arno/Projects/GitHub/CSL_Lima/projects/LegoReader/automaticScript.sh
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=Arno>
X-Cron-Env: <USER=Arno>
X-Cron-Env: <HOME=/Users/Arno>
Message-Id: <20190327162102.4555D187D9DC@Arno.local>
Date: Wed, 27 Mar 2019 12:21:00 -0400 (EDT)

Running Processing LegoReader!
Exception in thread "main" java.lang.ExceptionInInitializerError
        at processing.mode.java.runner.Runner.getSketchParams(Runner.java:478)
        at processing.mode.java.runner.Runner.launchVirtualMachine(Runner.java:209)
        at processing.mode.java.runner.Runner.launch(Runner.java:151)
        at processing.mode.java.Commander.<init>(Commander.java:283)
        at processing.mode.java.Commander.main(Commander.java:86)
Caused by: java.awt.HeadlessException
        at sun.awt.HeadlessToolkit.getMenuShortcutKeyMask(HeadlessToolkit.java:236)
        at processing.app.ui.Toolkit.<clinit>(Toolkit.java:93)
        ... 5 more
`````
